//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAndPlay.Commons.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeAndPlay.Commons.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las convocatorias se encuentran cerradas..
        /// </summary>
        public static string CONVOCATORIES_CLOSED {
            get {
                return ResourceManager.GetString("CONVOCATORIES_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales son inválidas..
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de control es inválido..
        /// </summary>
        public static string INVALID_CTRL_NUM {
            get {
                return ResourceManager.GetString("INVALID_CTRL_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de control es inválido o el taller no existe..
        /// </summary>
        public static string INVALID_CTRL_NUM_WORKSHOP {
            get {
                return ResourceManager.GetString("INVALID_CTRL_NUM_WORKSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos son inválidos..
        /// </summary>
        public static string INVALID_SEARCH_CRITERIA {
            get {
                return ResourceManager.GetString("INVALID_SEARCH_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algún miembro del equipo ya tiene un evento asignado..
        /// </summary>
        public static string INVALID_TEAM_COMPOSITION {
            get {
                return ResourceManager.GetString("INVALID_TEAM_COMPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del equipo o el número de control de los integrantes son inválidos o no se seleccionó un capitán..
        /// </summary>
        public static string INVALID_TEAM_DATA {
            get {
                return ResourceManager.GetString("INVALID_TEAM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del equipo ya está ocupado..
        /// </summary>
        public static string INVALID_TEAM_NAME {
            get {
                return ResourceManager.GetString("INVALID_TEAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño del equipo es inválido..
        /// </summary>
        public static string INVALID_TEAM_SIZE {
            get {
                return ResourceManager.GetString("INVALID_TEAM_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique que todos los miembros del equipo están registrados y pertenecen a Ing. en sistemas computacionales..
        /// </summary>
        public static string MEMBERS_NOT_REGISTERED_OR_GUESTS {
            get {
                return ResourceManager.GetString("MEMBERS_NOT_REGISTERED_OR_GUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante aun no se ha registrado o no pertenece a Ing. en sistemas computacionales..
        /// </summary>
        public static string NOT_REGISTERED_OR_GUEST {
            get {
                return ResourceManager.GetString("NOT_REGISTERED_OR_GUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró información usando esa criteria de búsqueda..
        /// </summary>
        public static string REPORT_HAS_NO_RECORDS {
            get {
                return ResourceManager.GetString("REPORT_HAS_NO_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecciona un evento al cual registrarás tu equipo..
        /// </summary>
        public static string SELECT_EVENT {
            get {
                return ResourceManager.GetString("SELECT_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, seleccione un taller al cual te registrarás..
        /// </summary>
        public static string SELECT_WORKSHOP {
            get {
                return ResourceManager.GetString("SELECT_WORKSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante ya tiene un taller asignado..
        /// </summary>
        public static string WORKSHOP_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("WORKSHOP_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El taller al que te intentas registrar ya no tiene cupo..
        /// </summary>
        public static string WORKSHOP_GROUP_FULL {
            get {
                return ResourceManager.GetString("WORKSHOP_GROUP_FULL", resourceCulture);
            }
        }
    }
}
