// <auto-generated />
namespace CodeAndPlay.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contact_rename_ticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_rename_ticket));
        
        string IMigrationMetadata.Id
        {
            get { return "201705260449597_contact_rename_ticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
