// <auto-generated />
namespace CodeAndPlay.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_sponsors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_sponsors));
        
        string IMigrationMetadata.Id
        {
            get { return "201705252004044_added_sponsors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
